language: csharp
mono: none
dotnet: 2.2.300
script:
 - dotnet pack -c Release -o . -p:PackageVersion=1.0.$TRAVIS_BUILD_NUMBER
 - dotnet nuget push AppLogger.1.0.$TRAVIS_BUILD_NUMBER.nupkg -k $nuget_key -s https://api.nuget.org/v3/index.json